### ISSUE TITLE
Website does not load

### ISSUE THREAD

**Issue by berkcan25** [berkcan25/ToDo#1]
When using the JavaScript compiled from Typescript, the site does not load, not in the browser with Github pages, nor with the live sever feature in VSC. 

See pictures below for reference
![image](https://github.com/berkcan25/ToDo/assets/103621562/44bad23c-0fc4-431c-94b0-e8105e2c6b3e)
![image](https://github.com/berkcan25/ToDo/assets/103621562/fc6510c3-f113-4f74-92d4-974dcf01a9bf)

**Comment by bartut22** [comment]
whats the console look like big dawg

**Comment by berkcan25** [comment]
Missed a while loop that was running infinitely

![image](https://github.com/berkcan25/ToDo/assets/103621562/cccd8154-d2f9-4ba5-be8e-b7f6f8dc7e26)
